### ISSUE TITLE
Rules: define how can we change the rules.

### ISSUE THREAD

**Issue by vbonvin** [vbonvin/IPT-public#1]
Idea: changes in the rules may be applied by the simple majority of the people who participated in vote.

**Comment by vbonvin** [comment]
Current state of the rules: nothing

Here is what I suggest:

in 1.1  General provision

> Any member of the IOC can suggest a modification to the rules. The executive committee is in charge of expressing the modification in a proper format. The whole IOC is thus asked to vote on each modification. The modification is accepted if more than 50% of the voters are in favor. In case of equal number of votes in favor and against the modification, the President has a decisive vote. The default voting period is 10 days.

Any thoughts ?

**Comment by Vovcick** [comment]
As for me it's ok. I would remove the word "thus" in the third sentence and after the last "10 days" I would add "after the letter regarding voting is sent to all IOC members"

**Comment by vbonvin** [comment]
Seems no one is complaining about it, thus I assume it to be good enough for IOC approval. I implemented Vladimir's comments and close this issue.
