### ISSUE TITLE
Guidelines to be published

### ISSUE THREAD

**Issue by LVoronina** [vbonvin/IPT-public#19]
I would like to publish 2 documents with the guidelines for the participants, which were developed last year.  I believe I had them circulating among the IOC already, but we do not have them on the website.  I attach the files here.  They are not binding documents, but a bunch of suggestions for the participants.  If there is no objections, I would put them together with FAQ. 

[IPT_Guidelines_from_the_jury.pdf](https://github.com/vbonvin/IPT-public/files/409303/IPT_Guidelines_from_the_jury.pdf)
[IPT_Guidelines_from_the_winners.pdf](https://github.com/vbonvin/IPT-public/files/409304/IPT_Guidelines_from_the_winners.pdf)

**Comment by vbonvin** [comment]
Fine be my,  we will put them [here](http://iptnet.info/faq/)
